### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by srinix07** [adityarn/PythonWorkshopIITM_LUG#1]
Which version should we use?? Python 2 or 3. The nb is written in 2 (I guess form the print statements). Is it too soon to use Python 3??

**Comment by adityarn** [comment]
No, it is not too soon. I have just been too lazy to get out of my comfort zone. I think it is indeed about time.

**Comment by srinix07** [comment]
In the notebook, AFAIK the only change required for Python 3 is add parenthesis in print statement.
`print "Hello! World"`
to 
`print("Hello world")`
